### ISSUE TITLE
A What's new section in the homepage.

### ISSUE THREAD

**Issue by GalacticCoder922** [PenguinMod/PenguinMod-Home#1]
I really want a **What's new** section in the homepage, where recent changes made to PenguinMod are shown. It would be split into 2 categories "Major Updates" and "Minor Updates". Major updates would be like the addition and removal of blocks and other noticeable changes. Minor updates would just be mainly bug fixes. And that concludes my suggestion.

**Comment by JeremyGamer13** [comment]
i actually didnt think about that but the home page would be a perfect spot for those kinds of things

**Comment by GalacticCoder922** [comment]
So are you going to add it or no?

**Comment by JeremyGamer13** [comment]
yea

**Comment by JeremyGamer13** [comment]
ill add it

**Comment by JeremyGamer13** [comment]
i couldnt replicate this exactly but something similar is on the site now

**Comment by GalacticCoder922** [comment]
It's exactly what I wanted! Thank you!
