### ISSUE TITLE
Out of date link that leads to GarboMuffin's profile

### ISSUE THREAD

**Issue by derpygamer2142** [PenguinMod/PenguinMod-Home#10]
When there is a compiling error, if you click on it it links to GarboMuffin's profile on scratch for reporting it. When I asked if their profile was the correct place to report bugs, he said to ask you to update your links.
(the issue i was experiencing was my fault apparently)

**Comment by JeremyGamer13** [comment]
this should be fixed now in https://github.com/PenguinMod/penguinmod.github.io/commit/1115703c431a97d98bef8f4cd38b8f4280e42c4f
