### ISSUE TITLE
Using PenguinMod extensions in Turbowarp

### ISSUE THREAD

**Issue by BlueDome77** [PenguinMod/PenguinMod-Home#12]
Is there any way for me to use PenguinMod extensions (or the extra blocks) in Turbowarp? It would be for personal use only.

Thanks!

**Comment by NOVASPIDERULTRA** [comment]
You can't. Penguinmod blocks don't work the same way as custom extensions on turbowarp.

**Comment by JoshAtticus** [comment]
No.
