### ISSUE TITLE
update desktop offline edition!

### ISSUE THREAD

**Issue by n0name-o0o0** [PenguinMod/PenguinMod-Home#13]
because my network problem, opening the web version is very slow and often "response time too long",and desktop version's last update is a year ago...

**Comment by RedMan13** [comment]
> because my network problem, opening the web version is very slow and often "response time too long",and desktop version's last update is a year ago...

thats because we have abandoned it

**Comment by RedMan13** [comment]
the desktop version i mean

**Comment by n0name-o0o0** [comment]
> > because my network problem, opening the web version is very slow and often "response time too long",and desktop version's last update is a year ago...
> 
> thats because we have abandoned it

so there's NO OFFLINE EDITORS??

**Comment by n0name-o0o0** [comment]
and for the web version, why removed the project video recorder?

**Comment by RedMan13** [comment]
> and for the web version, why removed the project video recorder?

its an addon, its just dissabled by default

**Comment by RedMan13** [comment]
> > > because my network problem, opening the web version is very slow and often "response time too long",and desktop version's last update is a year ago...
> > 
> > 
> > thats because we have abandoned it
> 
> so there's NO OFFLINE EDITORS??

yes

**Comment by n0name-o0o0** [comment]
so the way to use penguinmod offline is git clone it on the computer?

**Comment by n0name-o0o0** [comment]
> > so there's NO OFFLINE EDITORS??
> 
> yes

is clone the project on computer a way?
