### ISSUE TITLE
Discord Authentication Just Straight Up WON'T FUCKING WORK.

### ISSUE THREAD

**Issue by Zackanimates08** [PenguinMod/PenguinMod-Home#130]
![Screenshot 2024-10-21 070302](https://github.com/user-attachments/assets/9038d363-53b2-4c4e-ad6f-c650f0ffdae8)
![Screenshot 2024-10-21 065410](https://github.com/user-attachments/assets/d4618a36-4fce-4e2e-9dde-57e5e9df8486)
![Screenshot 2024-10-21 065403](https://github.com/user-attachments/assets/fd3ab343-7fb6-49b6-8f4d-39ef75175b3e)
I Let The IMAGES Do The Talking For Me.

**Comment by JeremyGamer13** [comment]
please do not create issues with this type of language or attitude, thanks.
discordauth is a community extension, meaning things may go down here and there. it seems to be online and working now
