### ISSUE TITLE
BUG(?): cannot open any file in iOS safari browser

### ISSUE THREAD

**Issue by n0name-o0o0** [PenguinMod/PenguinMod-Home#14]
its like this (about in 0:10)
i have to make bugs in ios file browser to open it
and there's also a bug processing huge block scripts in ios

**Comment by n0name-o0o0** [comment]
https://file.garden/Y37nYZOdi23QPRtp/videos/screen%20records/IMG_2428.PNG
https://file.garden/Y37nYZOdi23QPRtp/videos/screen%20records/RPReplay_Final1691108691.mp4
https://file.garden/Y37nYZOdi23QPRtp/videos/screen%20records/RPReplay_Final1691107419.mp4
problems

**Comment by JoshAtticus** [comment]
Hello, could you please let us know what device and iOS version you are running?

**Comment by JoshAtticus** [comment]
No response, closing as stale
