### ISSUE TITLE
Can’t login to heart a project

### ISSUE THREAD

**Issue by wwtv127** [PenguinMod/PenguinMod-Home#142]
so, whenever I try to heart a project, it says to login. I login and it does login to penguinmod, but when I press the heart button on a project, it still asks me to login. any reason why this happens?

**Comment by Ianyourgod** [comment]
i cant reproduce this issue so i dont really know how to help. I'm just gonna mark this as can't repro for now, please post a new comment if you can give any more information that may make this easier to reproduce.
