### ISSUE TITLE
It keeps saying methodnotconnected when i try to login

### ISSUE THREAD

**Issue by GreenwaveStudios** [PenguinMod/PenguinMod-Home#143]
I dunno why but it's pissing me off

**Comment by GreenwaveStudios** [comment]
> screenshot?

![image](https://github.com/user-attachments/assets/7b51529a-4a56-4bda-b4bb-c6a88c90e48b)

**Comment by Ianyourgod** [comment]
did you create your account with scratch

**Comment by GreenwaveStudios** [comment]
yeah i did but i tried it with github and chrome and they had errors too

**Comment by RedMan13** [comment]
qhhhpoooo

**Comment by RedMan13** [comment]
uhm, did you try ay of the other login methods to see if they work :trollface:

**Comment by GreenwaveStudios** [comment]
I quite literally said i did
![image](https://github.com/user-attachments/assets/7432f47b-0c37-418d-b403-bc71056ad5dd)

**Comment by RedMan13** [comment]
> I quite literally said i did ![image](https://private-user-images.githubusercontent.com/139999667/389218318-7432f47b-0c37-418d-b403-bc71056ad5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODcxODIsIm5iZiI6MTczMjM4Njg4MiwicGF0aCI6Ii8xMzk5OTk2NjcvMzg5MjE4MzE4LTc0MzJmNDdiLTBjMzctNDE4ZC1iNDAzLWJjNzEwNTZhZDVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxODM0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDM1NDJkNTQ3MzYyYTI5OTEwNDU1NTRkYTM3NDQxZmE3MDIzZDRjNGQ4NzM1MGJjZmE2MjNkMWFmMTBjYjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.auR0he5Nv6WLbLNhztfA2U46THTGr9oadGLLmSmj1mk)

no you did mot say that but ok

**Comment by RedMan13** [comment]
nsow the question passes back to ianyourgod

**Comment by GreenwaveStudios** [comment]
> > I quite literally said i did ![image](https://private-user-images.githubusercontent.com/139999667/389218318-7432f47b-0c37-418d-b403-bc71056ad5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODcxODIsIm5iZiI6MTczMjM4Njg4MiwicGF0aCI6Ii8xMzk5OTk2NjcvMzg5MjE4MzE4LTc0MzJmNDdiLTBjMzctNDE4ZC1iNDAzLWJjNzEwNTZhZDVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxODM0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDM1NDJkNTQ3MzYyYTI5OTEwNDU1NTRkYTM3NDQxZmE3MDIzZDRjNGQ4NzM1MGJjZmE2MjNkMWFmMTBjYjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.auR0he5Nv6WLbLNhztfA2U46THTGr9oadGLLmSmj1mk)
> 
> no you did mot say that but ok

I did 
![image](https://github.com/user-attachments/assets/86c4678b-ed98-4c8c-9eae-6f73ddd6a884)

**Comment by GreenwaveStudios** [comment]
I hate to necropost but this problem is genuinely pissing me off like I just want to make a penguinmod account i tried everything but nothing has been working.

**Comment by RedMan13** [comment]
are you on the sign up page or is your account your trying to access from before the api shut down

**Comment by RedMan13** [comment]
also i dont get why people make necto posting an issue.......... either way its not like a rule or anything here

**Comment by Ianyourgod** [comment]
wait so you cant create an account or you cant login to your already created account?

**Comment by GreenwaveStudios** [comment]
I fixed the problem. You have to SIGN UP with google. Not LOG IN.

**Comment by GreenwaveStudios** [comment]
I am so fucking stupid
