### ISSUE TITLE
[BUG] Unable to load unsandboxed extension

### ISSUE THREAD

**Issue by totchi-lagawi** [PenguinMod/PenguinMod-Home#149]
# Description
I am currently developing a Scratch extension. I tried to run it from the "Load custom extension" menu, using the textbox, however I got an error, saying that `Content at moz-nullprincipal:{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}?https://studio.penguinmod.com may not load data from blob:https://studio.penguinmod.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.` and `<script> source URI is not allowed in this document: “blob:https://studio.penguinmod.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx".`. There's nothing else, and so I'm quite confused about how this happened. The extension loads fine in TurboWarp.

# Reproduce the bug
- Open the extension menu
- Click on "Load custom extension"
- Go to "Text"
- Load the following extension unsandboxed
```javascript
class Extension {
    getInfo() {
        return {
            id: "extension",
            name: "Extension",
            blocks: [
                {
                    opcode: "block",
                    blocktype: "command",
                    text: "Hello world!"
                }
            ]
        }
    }

    block() {
        console.log("Hello world!")
    }
}

Scratch.extensions.register(new Extension())
```

**Comment by Ianyourgod** [comment]
it worked fine for me. what browser are you on? and what extensions do you have?

**Comment by totchi-lagawi** [comment]
Oh wow I should have been tired x)
I was talking about loading the extension sandboxed... Unsandboxed, it works. Sorry for the inconvenience...

**Comment by Ianyourgod** [comment]
its all good!

**Comment by totchi-lagawi** [comment]
No, the bug is still there!

**Comment by Ianyourgod** [comment]
oh oops i tested wrong. one second.

**Comment by totchi-lagawi** [comment]
Wait wait

**Comment by Ianyourgod** [comment]
just checked. this is a known bug. sorry!

**Comment by totchi-lagawi** [comment]
I think I remember why I opened this issue, and effectively I couldn't load the example in unsandboxed mode, which is a bug, but now it works fine.

**Comment by totchi-lagawi** [comment]
But it doesn't load in sandboxed mode? That's weird, although it is another bug.

**Comment by totchi-lagawi** [comment]
So since the extension loads fine in *unsandboxed* mode, this issue is now closed.
