### ISSUE TITLE
Extensions stop project from uploading

### ISSUE THREAD

**Issue by ZDev22** [PenguinMod/PenguinMod-Home#150]
I'm trying to upload a project, but it keeps hitting me with this error: 
![image](https://github.com/user-attachments/assets/5796475c-e7c7-41ae-ad39-3cc311bcead6)

Here are my extensions:
![image](https://github.com/user-attachments/assets/c413245c-be61-422f-9eea-f3ad6652d680)

**Comment by PuzzlingGGG** [comment]
your rank on pm needs to be penguin aka, upload 3 projects and be a account for a few days

**Comment by PuzzlingGGG** [comment]
![image](https://github.com/user-attachments/assets/0fa4bb7d-3bbb-4b7e-a271-6363da23ff2e)
![image](https://github.com/user-attachments/assets/b7b881a0-9ce4-44a6-a56b-8051e03b7e40)
