### ISSUE TITLE
Can you bring back cloud auth because new one doesn't work

### ISSUE THREAD

**Issue by MadeByRap** [PenguinMod/PenguinMod-Home#152]
I've tried like 20 times and new sign in always says error even know I try it everytime the right way, to respond to me back can you contact me on my scratch account @MadeByRap

**Comment by RedMan13** [comment]
your original account (before server shutdown) doesnt exist, you have to make a new one
if on your new account you have scratch as a login method then tour old account will be merged to the new one when we have those old accounts available

**Comment by Ianyourgod** [comment]
if its not the issue that gsa pointed out above, the captcha may just not be loading
