### ISSUE TITLE
Sign in with scratch not working - iOS

### ISSUE THREAD

**Issue by Fluffy728** [PenguinMod/PenguinMod-Home#154]
On iOS, I turned off block Popups but it is saying to turn it off even though popups are blocked. Now I can’t sign into my account MyScratchedAccount on penguin mod with Scratch, and no password is linked. What a restriction. Please fix this and help me, you and others!

**Comment by mariocraft987** [comment]
Same here!

**Comment by Ianyourgod** [comment]
you need popups enabled in order to sign in.

**Comment by Fluffy728** [comment]
It is enabled though.

**Comment by mariocraft987** [comment]
Yes, a popup shows up for me when I click "sign-in"
