### ISSUE TITLE
Brave Browser Error

### ISSUE THREAD

**Issue by asciibcla** [PenguinMod/PenguinMod-Home#155]
I wanted to search for projects, but when I opened PenguinMod, it felt like the website was unfinished. I couldn't click anything, I couldn't sign in or out, and pretty much everything was on the middle. Are the developers working on Brave support? I'm really confused, I even turned off my Brave shield and looked at the website settings, and everything setting was fine, except for PenguinMod itself.

**Comment by Ianyourgod** [comment]
Hi! this is a problem with vercel, that sadly we can't really fix.
There are steps, though, that may fix it on your side:
(do note that these steps are from someone on the discord server, not a developer

> open console, find script that's not working, open in new tab, reload until the script actually loads (the 404 page is incorrect), then clear the cache FROM THE SCRIPT PAGE (using the little settings looking icon in the top left)

**Comment by asciibcla** [comment]
I actually fixed it by restarting my computer somehow. Sorry for the disadvantage...
