### ISSUE TITLE
"{"error":"MethodNotConnected"}" when trying to login with scratch

### ISSUE THREAD

**Issue by GreenwaveStudios** [PenguinMod/PenguinMod-Home#157]
I have tried all 3 services that were added and NONE of them work.  They keep throwing the same {"error":"MethodNotConnected"} message. Please help

**Comment by Ianyourgod** [comment]
have you created an account? you need to create an account before you can login

**Comment by RedMan13** [comment]
also theres four login methods not three, have you tried name and pass?

**Comment by GreenwaveStudios** [comment]
Nevermind I found out you have to SIGN UP with google not LOG IN.
