### ISSUE TITLE
The ability to put projects on My Stuff without uploading projects.

### ISSUE THREAD

**Issue by GalacticCoderReturns** [PenguinMod/PenguinMod-Home#17]
I want the ability to put projects on My Stuff without having to upload the project. On the 3 dots on the project, on these projects, one of the options would be "Upload Project".

**Comment by RedMan13** [comment]
no...

**Comment by GalacticCoderReturns** [comment]
Darn it.

**Comment by GalacticCoderReturns** [comment]
Welp, time to close this issue.

**Comment by JeremyGamer13** [comment]
yea we dont have the server storage for this type of stuff

**Comment by GalacticCoderReturns** [comment]
Think they can do it with the unapproved project status.

**Comment by JeremyGamer13** [comment]
?

**Comment by GalacticCoderReturns** [comment]
Like making a project unapproved until it is sent for approval.

**Comment by JeremyGamer13** [comment]
we dont have the bandwidth or server storage available for that sadly

**Comment by GalacticCoderReturns** [comment]
Ok. That's weird...
