### ISSUE TITLE
A messages feature

### ISSUE THREAD

**Issue by ghost** [PenguinMod/PenguinMod-Home#2]
Like in Scratch, I want a messages feature. The only use it has (until studios, liking and favoriting, and related that gives you messages on Scratch) is checking if someone remixed your project (remix notifications) Please add this!

**Comment by GalacticCoderReturns** [comment]
Could someone reply to this?

**Comment by JeremyGamer13** [comment]
this will probably get added

**Comment by GalacticCoderReturns** [comment]
OK. Can you start working on it?

**Comment by JeremyGamer13** [comment]
theres a list of things either i or other devs are workin on https://trello.com/b/81m2XcKe/
this is kind of low priority since it would add more stuff to the api & home page (which take a while to get updates because its tedious)

**Comment by GalacticCoderReturns** [comment]
OK.

**Comment by GalacticCoderReturns** [comment]
Could someone close this?

**Comment by JeremyGamer13** [comment]
this can be reopened if features are missing that could be added to the messages feature
