### ISSUE TITLE
Utilize a Different Scratch Auth Frontend.

### ISSUE THREAD

**Issue by Steve0Greatness** [PenguinMod/PenguinMod-Home#20]
Hey! I'm aware of this project's relative popularity in the Scratch modding space. I'm also aware that PenguinMod uses the default provided front-end of Scratch Auth for authentication. This, on it's own, is not a problem. What is a problem, however, is that people frequently spam the comments section of Looky(the creator, owner, and primary-maintainer of Scratch Auth) with comments relating to issues they face while using PenguinMod.

I don't think anyone should be spammed, I hope you agree with me. Which is why I'm requesting that you stop using the unmodified front-end of Scratch Auth without changing it to make it clear that this project is not affiliated with Scratch Auth.

**What Do I Mean By "Front-End"**

Scratch Auth works with it's own backend API, an API that just happens to have CORs enabled, meaning it can be accessed from anywhere by both JS code, and _backend_ JS code. It's API is pretty ok-ly documented, although you have to do some digging. I already did this digging.

* **GET** https://auth.itinerary.eu.org/api/auth/getTokens
  _Query Options:_
  **redirect**\* - String ( base64 encoded url )
  method - Enum ( "cloud", "comment" )
  authProject - String ( ID of the Scratch project used for authentication )
* **GET** https://auth.itinerary.eu.org/api/auth/verifyTokens/:privateCode
  _Query Parameters:_
  **privateCode**\* - String ( private code given by `getTokens` )
  _Query Options:_
  **redirect**\* - String ( base64 encoded url, only required when `oneClickSignIn` is true )
  oneClickSignIn - Boolean
* **GET** https://auth.itinerary.eu.org/api/auth/oneClickSignIn
  _Headers:_
  **Authorization**\* - String
* **POST** https://auth.itinerary.eu.org/api/auth/oneClickSignIn/:username
  _Headers:_
  **Authorization**\* - String
  _Query Parameters:_
  **username**\* - String
  _Query Options:_
  **redirect** - String ( base64 encoded url )
* **DELETE** https://auth.itinerary.eu.org/api/auth/oneClickSignIn/:username
  _Headers:_
  **Authorization**\* - String
  _Query Parameters:_
  **username**\* - String

\* = required

Based off of [this image](https://user-images.githubusercontent.com/75220768/263859666-722bb72d-7f54-445c-bf7b-f28e3cf5c6fb.png) of a forum post on the original Scratch Auth Forum Topic(before it got dustbinned).

**Comment by RedMan13** [comment]
> people frequently spam the comments section of Looky
how would we fix this

**Comment by RedMan13** [comment]
and also how would we edit the front end of scratch auth?

**Comment by RedMan13** [comment]
nvm ignore that second comment

**Comment by JeremyGamer13** [comment]
there are a lot of long tasks related to the API so unfortunately this isn't gonna be able to happen soon

**Comment by Ianyourgod** [comment]
i think this is a good idea, ive seen that comment section. But as JG said we have other problems

**Comment by Steve0Greatness** [comment]
> i think this is a good idea, ive seen that comment section. But as JG said we have other problems

> there are a lot of long tasks related to the API so unfortunately this isn't gonna be able to happen soon.

That's fair. I just thought it'd be smart to bring this to yall's attention, as well as give details that could help solve it.

**Comment by Steve0Greatness** [comment]
I'm currently implementing this, see [Steve0Greatness/PenguinMod-Home:auth](https://github.com/Steve0Greatness/PenguinMod-Home/tree/auth) for progress. I'll make a PR when I finish it, and make it look nicer.

**Comment by JeremyGamer13** [comment]
if you ever finish it please mention me once its done so i can tell our translators to help translate it 👍 

> I'm currently implementing this, see [Steve0Greatness/PenguinMod-Home:auth](https://github.com/Steve0Greatness/PenguinMod-Home/tree/auth) for progress. I'll make a PR when I finish it, and make it look nicer.

**Comment by Steve0Greatness** [comment]
Alright, I'll let you know.

**Comment by Steve0Greatness** [comment]
It is (functionality wise) done. But it's not done in the looks department. Also, I cannot test it right now, because the project servers are down.

**Comment by Steve0Greatness** [comment]
@JeremyGamer13, I believe it's ready to be translated. Should I open a PR with maintainer contributions enabled?

**Comment by JeremyGamer13** [comment]
yea, maybe mark as draft

**Comment by Steve0Greatness** [comment]
> yea, maybe mark as draft

Alright!

**Comment by Steve0Greatness** [comment]
> yea, maybe mark as draft

A PR has been made now.
