### ISSUE TITLE
Mention (more) prominently that this is not allowed to be mentioned on Scratch

### ISSUE THREAD

**Issue by mybearworld** [PenguinMod/PenguinMod-Home#23]
I don't think too many people know about this, and therefore mention this mod on Scratch. It doesn't help that it's not in the mute filter at all. For examples, see https://scratch.mit.edu/discuss/topic/705721/

**Comment by JeremyGamer13** [comment]
im not really sure what we can do besides slap a huge message on the website which would look pretty ugly and confusing to outsiders

**Comment by mybearworld** [comment]
Maybe just if you're logged out, or maybe if you try to log in for the first time (related to #20)?

**Comment by JeremyGamer13** [comment]
alternatively, is there a way to tell the scratch team to add penguinmod as a blocked term?

**Comment by mybearworld** [comment]
> alternatively, is there a way to tell the scratch team to add penguinmod as a blocked term?

Contact Us

**Comment by JeremyGamer13** [comment]
> Maybe just if you're logged out, or maybe if you try to log in for the first time (related to #20)?

actually i think having our own scratch auth frontend would help with this since we could mention this in an error message if something went wrong or just place it at the bottom
unfortunately october is gonna be a lot of API + home page features so ideally i don't want to remake the auth system during that

**Comment by mybearworld** [comment]
> actually i think having our own scratch auth frontend would help with this since we could mention this in an error message if something went wrong or just place it at the bottom
> unfortunately october is gonna be a lot of API + home page features so ideally we don't want to remake the auth system during that

So, wouldn't adding a message be a good fix for now, and then it could be dealt with properly later?

**Comment by JeremyGamer13** [comment]
![image](https://github.com/PenguinMod/PenguinMod-Home/assets/69337718/e362aea4-06b2-4a36-b771-09d3055b12bf)
like this?

**Comment by mybearworld** [comment]
That looks great!

**Comment by JeremyGamer13** [comment]
this should be on the site now, not sure if its enough but it should be clear enough

**Comment by Dark-211** [comment]
use cookies to check if its the user's first time on the website and use the banner with the X on the right
(i dont know i just making stuff up)

**Comment by RedMan13** [comment]
COOKIES?!?!?!!!?!?!?!?!?!?!?!?!

**Comment by Dark-211** [comment]
idk
donate to pm to get a free cookie (not guaranteed)

**Comment by Dark-211** [comment]
![image](https://github.com/PenguinMod/PenguinMod-Home/assets/141400194/b98c4f1e-5b49-4362-9c4d-fc9ea2440f33)

**Comment by mybearworld** [comment]
> ![image](https://user-images.githubusercontent.com/141400194/271851969-b98c4f1e-5b49-4362-9c4d-fc9ea2440f33.png) its seems that yall already use em

Yeah, they'd be necessary to log in

**Comment by RedMan13** [comment]
i dont actually know whats using the cookies ._.

**Comment by Dark-211** [comment]
true...

**Comment by RedMan13** [comment]
i only see one coockie and thats from cloudflare deciding that i can be allowed to the site

**Comment by hdboye** [comment]
PenguinMod is allowed to be mentioned on Scratch. There is no rule that states that Scratch modifications aren't allowed to be mentioned. There's even a **stickied** forum post with a list full of Scratch mods. Also, even if it was, that'd be the user's responsibility and not PenguinMod's.

**Comment by JeremyGamer13** [comment]
we are also just more lenient on what we allow so stuff like curse words can get through on the platform if they arent over the top

**Comment by hdboye** [comment]
Even if it's not allowed, I don't see why it would be PM's responsibility to ensure that people don't mention it

**Comment by mybearworld** [comment]
> Even if it's not allowed, I don't see why it would be PM's responsibility to ensure that people don't mention it

It's not, but it's a nice thing to do because it's much easier to do it from PenguinMod's side than from Scratch's.
