### ISSUE TITLE
wow. why did you do that on penguinmod

### ISSUE THREAD

**Issue by ZackFavors02** [PenguinMod/PenguinMod-Home#26]
you just said "Due to schedule changes, systems we need to rework, and a lot of small bugs preventing updates from working last minute, we'll now just drop one update on the 1 year day to hopefully make sure everything works well and we have time for it. Hope you can understand <:good:1118293837773807657> @Update Ping"

**Comment by JeremyGamer13** [comment]
the message says why we did it idk

**Comment by Ianyourgod** [comment]
if you read what you sent you'd know the reason
