### ISSUE TITLE
Change domain

### ISSUE THREAD

**Issue by WojtekCodesToday** [PenguinMod/PenguinMod-Home#3]
why vercel default url (`https://penguinmod-home.vercel.app/`) when yall could use `penguinmod.site` to use the home page and have `/editor` as a page.

this is a issue literally.

**OUTSIDE THE BOX:**
also if solved, can i be a contributor?

**Comment by emmettdewet14** [comment]
home.penguinmod.site 🤣

**Comment by WojtekCodesToday** [comment]
> home.penguinmod.site 🤣

subdomains can be an issue to money though, but not solved yet...

**Comment by JeremyGamer13** [comment]
we have free subdomains it seems, also we are already trying this

**Comment by WojtekCodesToday** [comment]
> we have free subdomains it seems, also we are already trying this

yeah let's see how long they will become alive.

**Comment by JeremyGamer13** [comment]
we only have the domain for a certain amount of time

**Comment by WojtekCodesToday** [comment]
> we only have the domain for a certain amount of time

this is what i meant.

**Comment by JeremyGamer13** [comment]
frogot to mark this as closed since we moved domains a while ago

**Comment by WojtekCodesToday** [comment]
💀, anyways yayy
