### ISSUE TITLE
BUG: Deleting an extension leaves the blocks that belong to it and will corrupt projects

### ISSUE THREAD

**Issue by BlestLace** [PenguinMod/PenguinMod-Home#32]
I am working on some engine to fetch time via JavaScript but, the last time I saved it, when I closed my browser window, I couldn't open it anymore.

An alert appeared on my browser, saying the following:

> Unable to load project: Error: Unknown extension: localstorage

Restore points don't work aswell.
Is there a way to recover projects?

**Comment by BlestLace** [comment]
If you need the .pmp, here it is.
[Project.zip](https://github.com/PenguinMod/PenguinMod-Home/files/13064378/Project.zip)

**Comment by BlestLace** [comment]
Hey, so I found the solution.
Make the ".pmp" file a ".zip" file by renaming it.
Open the "project.json" file inside the zip with Visual Studio.
Then, go to the end of the file and you'll see something like:
`  "extensionData": {},
  "extensions": [ "utilities", "jgJavascript", "SPtimeCalc" ],
  "extensionURLs": {
    "utilities": "https://extensions.turbowarp.org/utilities.js",
    "SPtimeCalc": "https://extensions.penguinmod.com/extensions/SharkPool/Time-Calculations.js"
  },`

The problem is caused by blocks in the project that belong to the extension, and the extension being undefined.

**Comment by polygoners1** [comment]
so, the project file pls?

**Comment by BlestLace** [comment]
Well, I fixed the problem but if you need it, I sent it above. Just in case, I'm gonna reattach it here.
[Project.zip](https://github.com/PenguinMod/PenguinMod-Home/files/13296866/Projet.2.zip)

**Comment by polygoners1** [comment]
> Well, I fixed the problem but if you need it, I sent it above. Just in case, I'm gonna reattach it here. [Project.zip](https://github.com/PenguinMod/PenguinMod-Home/files/13296866/Projet.2.zip)

when i tried to open it, it said "Could not load project: Error: Unknown extension: localstorage".

**Comment by BlestLace** [comment]
exactly 💀

**Comment by BlestLace** [comment]
I fixed it by modifying the JSON inside

**Comment by polygoners1** [comment]
ye

**Comment by polygoners1** [comment]
uhhhh, hello?

**Comment by polygoners1** [comment]
> OHH you want the finished result, right?

i do want it

**Comment by BlestLace** [comment]
oh sorry i forgot to check my github

**Comment by BlestLace** [comment]
why do you need it?

**Comment by polygoners1** [comment]
> why do you need it?

i just wanna see

**Comment by BlestLace** [comment]
alright let me see where i put it
i'll give it to you tomorrow

**Comment by polygoners1** [comment]
> alright let me see where i put it i'll give it to you tomorrow

epic

**Comment by BlestLace** [comment]
sorry for the wait i can't find it 💀💀
tomorrow i promise

**Comment by polygoners1** [comment]
> sorry for the wait i can't find it 💀💀 tomorrow i promise

oh

**Comment by RedMan13** [comment]
oh shit yeah i still need to work on this

**Comment by BlestLace** [comment]
It turns out i didn't even have it.
I'll repair the project with the link I referenced 3 - 4 weeks ago

**Comment by BlestLace** [comment]
> oh shit yeah i still need to work on this
> 

Thanks 👍

**Comment by polygoners1** [comment]
> It turns out i didn't even have it. I'll repair the project with the link I referenced 3 - 4 weeks ago

nice

**Comment by polygoners1** [comment]
where the file
![disintegrate](https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/1e863a3f-5115-4e98-a730-75e9317080fc)
![disintegrate](https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/1e863a3f-5115-4e98-a730-75e9317080fc)
![disintegrate](https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/1e863a3f-5115-4e98-a730-75e9317080fc)
![disintegrate](https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/1e863a3f-5115-4e98-a730-75e9317080fc)
![disintegrate](https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/1e863a3f-5115-4e98-a730-75e9317080fc)

**Comment by BlestLace** [comment]
i forgor 💀

**Comment by BlestLace** [comment]
ok it's here
[pmp.zip](https://github.com/PenguinMod/PenguinMod-Home/files/13452422/pmp.zip)

I put a phone ringtone to test it.
in the stage there's a "When (getTime) received" block with my custom block associated to it:
"Play sound (   ) at (hh:mm:ss) until done"
If you want to test it keep the bootaudio there and choose a custom time.
"bootaudio" will either wait until that specified time to play or it will automatically play at a certain second if that time has already been reached (so the sound is synchronized with the time you put)
btw local storage extension is useless lmao

**Comment by BlestLace** [comment]
Sorry for the wait lol

**Comment by BlestLace** [comment]
Wait js time actually uses your local pc time FUUU-

**Comment by BlestLace** [comment]
Bro nvm this is broken

**Comment by polygoners1** [comment]
well, i made my own play sound custom block :
[here it is!](https://github.com/PenguinMod/PenguinMod-Home/files/13453146/play.sound.zip)

**Comment by BlestLace** [comment]
Whoa how'd you get that sound selector?

**Comment by BlestLace** [comment]
That's not what I was expecting but that's pretty cool

**Comment by polygoners1** [comment]
> Whoa how'd you get that sound selector?

the "all menus" extension just put this : https://extensions.penguinmod.com/extensions/Lily/AllMenus.js into the custom extension thingy

**Comment by BlestLace** [comment]
oh that's pretty cool
