### ISSUE TITLE
make me a custom badge

### ISSUE THREAD

**Issue by pickaxestudios** [PenguinMod/PenguinMod-Home#43]
so i want a custom badge btw i can't do pull requests btw so my pm user is 
tds_99888777

discord: pngb

**Comment by JeremyGamer13** [comment]
we dont... currently do these

**Comment by Ianyourgod** [comment]
why would we even do this?

**Comment by derpysschoolaccount** [comment]
bruh i'm not a dev but this is dumb

**Comment by RedMan13** [comment]
> so i want a custom badge btw i can't do pull requests btw so my pm user is tds_99888777
> 
> discord: pngb

why.

**Comment by RedMan13** [comment]
bruh i thought there was a close as rejected :skull:

**Comment by derpysschoolaccount** [comment]
here's your badge: https://bit.ly/urmomhehehe

**Comment by polygoners1** [comment]
> here's your badge: https://bit.ly/urmomhehehe

I KNEW IT WAS A RICKROLL!
