### ISSUE TITLE
REMOVE ADS

### ISSUE THREAD

**Issue by polygoners1** [PenguinMod/PenguinMod-Home#47]
what the hell did they do? just, you get donations already! you don't need ads!

**Comment by derpygamer2142** [comment]
This is not an actual issue.

**Comment by RedMan13** [comment]
> what the hell did they do? just, you get donations already! you don't need ads!

maby donate then cus we only have like 3 dollars rn from donations

**Comment by JeremyGamer13** [comment]
our first ad setup went horribly so i am reconsidering it

**Comment by Ianyourgod** [comment]
> you get donations already
we have gotten like less than 10 dollars in the 2 months we have had them. our severs cost around 4 dollars a month. that leaves us with 1 dollar a month for everything else. Our domain costs 10 dollars a year. That leaves us with 2 dollars a year for everything else.

**Comment by Ianyourgod** [comment]
(this is if we get 5 dollars a month)

**Comment by Ianyourgod** [comment]
(which we dont, we get way less)

**Comment by Ianyourgod** [comment]
Currently, we dont pay for server hosting. Our lovely server host provides it for free. But I don't want to just like leave him with that because that's rude.
