### ISSUE TITLE
It's blocked

### ISSUE THREAD

**Issue by s-aarchen** [PenguinMod/PenguinMod-Home#48]
It just says "reset" in Times New Roman. I tried to deploy it, but I don't know how!

**Comment by Ianyourgod** [comment]
what says that????? you can’t just say “it”. that’s not how pronouns work

**Comment by SharkPool-SP** [comment]
> what says that????? you can’t just say “it”. that’s not how pronouns work

He's trying not to get cancelled for using the wrong pronouns :trollface:

**Comment by RedMan13** [comment]
> It just says "reset" in Times New Roman. I tried to deploy it, but I don't know how!

well thats your fault since nothing we have will give you that output

**Comment by s-aarchen** [comment]
> what says that????? you can’t just say “it”. that’s not how pronouns work

um the website

**Comment by s-aarchen** [comment]
sorry for not being clear

**Comment by RedMan13** [comment]
> sorry for not being clear

i thought you where quite clear
