### ISSUE TITLE
Move the terms.html and privacy.html from studio.PenguinMod to here.

### ISSUE THREAD

**Issue by Steve0Greatness** [PenguinMod/PenguinMod-Home#49]
I don't believe I need much more of an explanation for this. Also, about previous links being broken, you can place this code(below) as the content for the previous HTML content(just make sure to replace the ... with the path to the new route).

```
<meta http-equiv="refresh" content="0; URL='https://penguinmod.com/...'" />
```

This would introduce more consistency in URLs. Also, having the header on these pages would be nice as well.

**Comment by RedMan13** [comment]
nuh uh

**Comment by Steve0Greatness** [comment]
It took half an hour to do it on my own branch: [Steve0Greatness/PenguinMod-Home:move-over-terms-&-privacy-policy](https://github.com/Steve0Greatness/PenguinMod-Home/tree/move-over-terms-&-privacy-policy)

**Comment by RedMan13** [comment]
![nuh uh](https://github.com/PenguinMod/PenguinMod-Home/assets/74981904/ec7fceac-0778-4cd6-b13a-02d149eefca1)

**Comment by Steve0Greatness** [comment]
Literally 1984.

**Comment by RedMan13** [comment]
bro calls it 1984 just because a developer said "no" to "move this thing that doesnt need moved" 💀

**Comment by Steve0Greatness** [comment]
Sure, but a different front-end for Scratch Auth isn't really needed either. This is basically just about having more consistency in the UX. Plus, moving them here would just allow for the usual site header to be used, in addition to the user's theme choice. In addition to that: translation.

**Comment by RedMan13** [comment]
thats not true
we do need a new scratch-auth front-end

**Comment by Steve0Greatness** [comment]
> thats not true we do need a new scratch-auth front-end

Well, functionality wise it's all that's really needed, unless what you're talking about is translations. If it is what you're talking about, then how about translations on the TOS and Privacy Policy files?

**Comment by RedMan13** [comment]
that wasnt your argument now is it mate

**Comment by JeremyGamer13** [comment]
this argument is useless, ill move the files later

**Comment by JeremyGamer13** [comment]
accidentally closed

**Comment by Steve0Greatness** [comment]
> this argument is useless, ill move the files later

I've pretty much already done this on my own fork: [Steve0Greatness/PenguinMod-Home:move-over-terms-&-privacy-policy](https://github.com/Steve0Greatness/PenguinMod-Home/tree/move-over-terms-&-privacy-policy).

**Comment by Ianyourgod** [comment]
> It took half an hour to do it on my own branch: [Steve0Greatness/PenguinMod-Home:move-over-terms-&-privacy-policy](https://github.com/Steve0Greatness/PenguinMod-Home/tree/move-over-terms-&-privacy-policy)

erm... pr?
