### ISSUE TITLE
Allow Login using GitHub or other services

### ISSUE THREAD

**Issue by The4thPlayer** [PenguinMod/PenguinMod-Home#51]
Can you add signing in through Github?
I don't have access to any of my Scratch accounts anymore.
(i broke their tos allegedly and they banned all of my accounts)
So I can't use the sign in through Scratch feature.

**Comment by Steve0Greatness** [comment]
I'm not currently aware of any plans to allow signing through GH. However, I would like to say that if it were, PenguinMod would likely have to migrate all accounts to an entirely different account system(so independent PenguinMod accounts). In other words: it'd be a nightmare to implement, so it (probably) won't be.

Of course, I'm not a developer for PenguinMod, so I don't really know the developers' plans on the accounts system.

**Comment by RedMan13** [comment]
we already have plans in place to migrate all accounts to a proper account system instead of relying uppon scratch

**Comment by Steve0Greatness** [comment]
> we already have plans in place to migrate all accounts to a proper account system instead of relying uppon scratch

Alright! Would that mean that GitHub could be used as an OAuth method(or even other OAuth providers like Google or X/Twitter)? Or, are there no current plans on OAuth?

**Comment by RedMan13** [comment]
because of scratch account logins existing it will probably have oauth in some way

**Comment by The4thPlayer** [comment]
Epic, ya'll made any progress so far?

**Comment by The4thPlayer** [comment]
dang
