### ISSUE TITLE
Addon Bug: Running block border

### ISSUE THREAD

**Issue by YogaindoCR** [PenguinMod/PenguinMod-Home#58]
This addon doesn't work on PenguinMod and I really need them to understand the new block in PenguinMod
![image](https://github.com/PenguinMod/PenguinMod-Home/assets/132117105/ac1b1610-33bd-4961-a149-83f2c6caf0cc)

In PenguinMod:
![image](https://github.com/PenguinMod/PenguinMod-Home/assets/132117105/1a26815c-904b-48d0-b3d9-0ec888728a0c)

It should be like this:
![image](https://github.com/PenguinMod/PenguinMod-Home/assets/132117105/3aadd5ef-5bd6-4090-9be5-bd1ce9ada031)

**Comment by RedMan13** [comment]
you cant dissable the compiler in penguinmod

**Comment by YogaindoCR** [comment]
> you cant dissable the compiler in penguinmod

Oh, How about the optimization? Is think that is the compiler but with different names

**Comment by JeremyGamer13** [comment]
dangerous optimizations just remove certain features in favor of speed

**Comment by JeremyGamer13** [comment]
this addon might just be removed in the future instead, penguinmod basically relies on the compiler and at the moment this cant be implemented into the compiler without a lot of performance setbacks
