### ISSUE TITLE
Moderate "C2A" to make sure it is properly crediting people

### ISSUE THREAD

**Issue by nmsderp** [PenguinMod/PenguinMod-Home#67]
## Hello!
Recently, I have noticed that people use C2A (Credit to all) in their projects. This is an issue because the original creator(s) are not getting any credit. Users may begin to take projects from lesser-known Scratch users and upload it to PenguinMod with no changes (or minimal changes.) This could lead to the many C2A dramas on Scratch, but on PenguinMod. So I feel the term C2A and other variations should be blocked from being added to the title, instructions and notes and credits to stop any conflict.
  
But hey what do I know. :trollface:

PS: There is a really good project that goes into more detail: https://scratch.mit.edu/projects/710417651/

**Comment by JeremyGamer13** [comment]
we can add C2A to our moderation system if that works (so we know which projects use it & if they use it where it credits properly)

**Comment by nmsderp** [comment]
That would work

**Comment by JeremyGamer13** [comment]
will keep this open until its implemented in the api then

**Comment by JeremyGamer13** [comment]
ah i left this issue open after resolving it, this is now in the api
