### ISSUE TITLE
i am having problems getting the home menu to connect to my servers

### ISSUE THREAD

**Issue by cubers93** [PenguinMod/PenguinMod-Home#72]
https://github.com/PenguinMod/PenguinMod-Home/assets/101417971/27435410-e2e4-4404-84e7-14a68025097b

**Comment by RedMan13** [comment]
math dot em pea four

**Comment by cubers93** [comment]
> math dot em pea four


https://github.com/PenguinMod/PenguinMod-Home/assets/101417971/c72d072d-dad3-4247-bd29-63c0cabd0369

**Comment by RedMan13** [comment]
man what du hail wen did GitHub add ads to comments :skull:

**Comment by cubers93** [comment]
> man what du hail wen did GitHub add ads to comments 💀


Uploading troll.mov…

**Comment by RedMan13** [comment]
> > man what du hail wen did GitHub add ads to comments 💀
> 
> Uploading troll.mov…

epic upload failure

**Comment by JeremyGamer13** [comment]
what is the exact problem pleas

**Comment by cubers93** [comment]
> what is the exact problem pleas


https://github.com/PenguinMod/PenguinMod-Home/assets/101417971/39b847fe-ae3a-4e5a-b174-a4f41cf57389

**Comment by RedMan13** [comment]
oh oops 8 thought this was closed
