### ISSUE TITLE
the penguinmod forums

### ISSUE THREAD

**Issue by SpareEnderboy** [PenguinMod/PenguinMod-Home#75]
i just enabled 2fa on my github account yay
i used microsoft authenticatoe

**Comment by SpareEnderboy** [comment]
welcome to the penguinmod forums
issue #75 on PenguinMod-Home
this is a forum thread on github so of course you can use _**markdown**_
### DONT CLOSE THIS ISSUE

**Comment by SharkPool-SP** [comment]
https://github.com/PenguinMod/PenguinMod-Home/discussions

:trollface:

**Comment by SpareEnderboy** [comment]
> https://github.com/PenguinMod/PenguinMod-Home/discussions
> 
> ### :trollface:

im dubm
