### ISSUE TITLE
CopyRight Rule Change Suggestion

### ISSUE THREAD

**Issue by wwtv127** [PenguinMod/PenguinMod-Home#77]
So I Feel Like The CopyRight Rule Is A Little Too Strict. So I Feel Like The New CopyRight Rule Should Be “If You Use Any Copyright Content, You Project Will Be Removed Unless You Give Credit To The Original Person Or Company” It Kinda Makes Sense Because Copyright Doesn’t Technically Happen Unless You Make Money Off Of It.

**Comment by SharkPool-SP** [comment]
Bro does NOT know how Copyright Law works 💀

**Comment by wwtv127** [comment]
> Bro does NOT know how Copyright Law works 💀

actually someone on discord agreed to my change

**Comment by SharkPool-SP** [comment]
> > Bro does NOT know how Copyright Law works 💀
> 
> actually someone on discord agreed to my change

So? It’s not like that magically changes the law

**Comment by wwtv127** [comment]
> law

ok? then why doesn’t scratch have that law then? literally i see so much copyright content on scratch and none got reported.

**Comment by JeremyGamer13** [comment]
the copyright rule is specifically that you are responsible for what you include & we will remove your project if we are told to by the original copyright owner.
in the case of youtube for example, they have already gone after discord bots for using their videos without including ads for example.

> > law
> 
> ok? then why doesn’t scratch have that law then? literally i see so much copyright content on scratch and none got reported.

**Comment by wwtv127** [comment]
one more question before i go. is a project where you upload videos allowed on penguinmod if i credit the person who uploaded it?

**Comment by JeremyGamer13** [comment]
uploading videos would bring a moderation concern so no

**Comment by wwtv127** [comment]
> uploading videos would bring a moderation concern so no

wow. for someone who literally allows uploading and downloading projects on penguinmod.

**Comment by JeremyGamer13** [comment]
because we take a look through them? our moderators arent gonna look through your projects uploads every day
