### ISSUE TITLE
A Weird Glitch That I Found

### ISSUE THREAD

**Issue by wwtv127** [PenguinMod/PenguinMod-Home#78]
So If You Use One Device To Sign In To Penguinmod And Try Using Another Device To Log in As Well, The Other Device Gets Logged Out Of Penguinmod. Why?

**Comment by JeremyGamer13** [comment]
penguinmod just sets your account to have a single login session code when you login, i have been thinking about allowing devices to share a session or just make multiple sessions on the same account though
