### ISSUE TITLE
Can Someone Tell Me If There Is A New Unofficial Forum Page Yet?

### ISSUE THREAD

**Issue by wwtv127** [PenguinMod/PenguinMod-Home#79]
So A Little While Back, I Mentioned How I Wanted A Forum Page On PenguinMod And One Guy Said He Would Make It For Us. So He Did But Then, It Got Removed Due To The Forum Page Being Really Buggy. Than A Few Days Later, He Made Another Forum Page But He Said It Was A Demo. That's The Last Time I Heard Anything About The Forum Because I Have Since Left Discord. So Is There Any New Updates On The Unofficial Forum Page?

**Comment by JeremyGamer13** [comment]
this is not the place to ask for support on an unofficial thing not created by us, we cant help you & you need to message the creator of that instead

**Comment by wwtv127** [comment]
> this is not the place to ask for support on an unofficial thing not created by us, we cant help you & you need to message the creator of that instead

Well I Dont Know The Creators Email

**Comment by JeremyGamer13** [comment]
cant help you there then
