### ISSUE TITLE
New block

### ISSUE THREAD

**Issue by GalacticCoder922** [PenguinMod/PenguinMod-Home#8]
(ask ()), which would do the ask function and then report the answer.

**Comment by RedMan13** [comment]
sounds like [YOUR MOM]

**Comment by JeremyGamer13** [comment]
> (ask ()), which would do the ask function and then report the answer.

https://github.com/PenguinMod/PenguinMod-Vm or in the Discord would be the place for block suggestions
ill think about this tho
