### ISSUE TITLE
cant log back in

### ISSUE THREAD

**Issue by polygoners1** [PenguinMod/PenguinMod-Home#85]
i logged out and i cant log back in for some reason. please just add a password log in. wait... it wont let me use the password log in on the forum. JUST FIX YOUR DUMB AUTHENTICATION ALREADY!

**Comment by polygoners1** [comment]
oh wait the forum has its own log in system

**Comment by polygoners1** [comment]
oh wait i just got back in!

**Comment by JeremyGamer13** [comment]
the server is having issues at the moment (supposedly one of our database files broke)

**Comment by polygoners1** [comment]
> the server is having issues at the moment (supposedly one of our database files broke)

hold in i need to save a file in here 
![Screenshot 2024-03-21 5 05 46 PM](https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/fb22187a-5fd2-4152-a787-2023d286e0fa)

**Comment by polygoners1** [comment]
> > the server is having issues at the moment (supposedly one of our database files broke)
> 
> hold in i need to save a file in here ![Screenshot 2024-03-21 5 05 46 PM](https://private-user-images.githubusercontent.com/149721398/315755349-fb22187a-5fd2-4152-a787-2023d286e0fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNjAwMTksIm5iZiI6MTcxMTA1OTcxOSwicGF0aCI6Ii8xNDk3MjEzOTgvMzE1NzU1MzQ5LWZiMjIxODdhLTVmZDItNDE1Mi1hNzg3LTIwMjNkMjg2ZTBmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQyMjIxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODk0Y2I2OGQ3NjI5YzQ1N2U2ZTIwODQ3OWYxOWI2Yjg3YjM3M2I5NDkxOTNkMmUyYTJmNTIzMGIxMmFlMWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tsYENBXZcSuUaAu82J7Z0Ch6tBB6jxnAmXpnrsn2ijQ)
> 
> done (btw it took me like, 45 minuets to get the image from guest mode to my main chrome account) (OH CRAP THERE IS A MISSPLELLING)

ok take 2
![Screenshot 2024-03-21 5 20 43 PM](https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/04fdfca2-1647-48ff-a2f9-328553a3cfa0)

**Comment by polygoners1** [comment]
another file save. why not?
[Ulterior motives lyrics.txt](https://github.com/PenguinMod/PenguinMod-Home/files/15301153/Ulterior.motives.lyrics.txt)

**Comment by polygoners1** [comment]
uhhh i have a yt channel. (@thatepic1gd) so this is footage for the video.

https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/a158a681-e7b8-4a15-8ec7-097d12b498fb

**Comment by polygoners1** [comment]
https://github.com/PenguinMod/PenguinMod-Home/assets/149721398/97b61e0f-5323-4ac6-9b11-06125f456cb6
