### ISSUE TITLE
The Project Server Is Glitching Out

### ISSUE THREAD

**Issue by wwtv127** [PenguinMod/PenguinMod-Home#89]
Why Is The Project Server Glitching Out? Give Me Some Context @JeremyGamer13

**Comment by Steve0Greatness** [comment]
See header on https://penguinmod.com/

**Comment by immortalbean** [comment]
Server is planned to be back up on the 20th

**Comment by immortalbean** [comment]
It says here that maintenance is planned to end on the 20th https://status.penguinmod.com/maintenance/375686
