### ISSUE TITLE
Support Ticket

### ISSUE THREAD

**Issue by Cameron97102** [PenguinMod/PenguinMod-Home#92]
**THIS IS FROM THE SCCPSTEVE FOUNDATION GROUP. ALL MESSAGES FROM DEVELOPERS AND ANY OTHER HUMAN BEING WILL BE REPORTED IF THERE IS ANY NOT APPROPRIATE LANGUAGE. THANKS.**

_Hello PenguinMod Devs._ I have requested you add a URL for redirect when your google account gets linked, because I AM WORKING ON A PROJECT AND AM FURIOUS WHEN YOU DO NOT ANSWER MY EMAILS. I REQUEST ONE MORE TIME, BEFORE I STOP USING YOU FOR MY PROJECTS AT WORK, TO ADD A URL THAT REDIRECTS TO YOUR PROJECT SENDING DATA OVER FROM YOUR GOOGLE ACCOUNT. LIKE I SAID, I WILL MAKE THE CODE. THANKS, AND **_GET BETTER AT RESPONDING_**

**Comment by JeremyGamer13** [comment]
please explain what you want us to do better, a screaming rage doesnt exactly help tell us what you want

**Comment by RedMan13** [comment]
> **THIS IS FROM THE SCCPSTEVE FOUNDATION GROUP. ALL MESSAGES FROM DEVELOPERS AND ANY OTHER HUMAN BEING WILL BE REPORTED IF THERE IS ANY NOT APPROPRIATE LANGUAGE. THANKS.**
> 
> _Hello PenguinMod Devs._ I have requested you add a URL for redirect when your google account gets linked, because I AM WORKING ON A PROJECT AND AM FURIOUS WHEN YOU DO NOT ANSWER MY EMAILS. I REQUEST ONE MORE TIME, BEFORE I STOP USING YOU FOR MY PROJECTS AT WORK, TO ADD A URL THAT REDIRECTS TO YOUR PROJECT SENDING DATA OVER FROM YOUR GOOGLE ACCOUNT. LIKE I SAID, I WILL MAKE THE CODE. THANKS, AND **_GET BETTER AT RESPONDING_**

i dont get it

**Comment by RedMan13** [comment]
what do yo meeeen redirect

**Comment by RedMan13** [comment]
d you meana special text embed for google accounts?

**Comment by RedMan13** [comment]
9h yeah i should che k the pm email shouldnt i

**Comment by SharkPool-SP** [comment]
Im gonna close this from inactivity. @Cameron97102 get better at responding :trollface:
