### ISSUE TITLE
Why is server down for a while?

### ISSUE THREAD

**Issue by badu888** [PenguinMod/PenguinMod-Home#96]
PenguinMod project server is down for a while, it's been like month or more since project server are down. What did happen?

**Comment by derpygamer2142** [comment]
Read the banner at the top of the page

**Comment by badu888** [comment]
yeah i readed it before alot. is server fixing planned?

**Comment by JeremyGamer13** [comment]
its nearly done (no exact date yet)

**Comment by badu888** [comment]
oh ok thx

**Comment by badu888** [comment]
i see sharkpool closed issue. ok i will be patient
